//Aquí va la data de firestore database
let LoopBuilding = {
  Empresas: [
    "Sourceful",
    {
      Personal: ["Tom Collins", "Tania Juárez", "Leonardo Torres"],
      Encargado: "Mariana Vallejo",
      Registro: {
        Nombre: "",
        Apellido: "",
        Correo: "",
        Teléfono: "",
        "motivo de la visita": [
          entrevista,
          paqueteria,
          personal,
          reunion,
          estudiante,
          otro,
        ],
        "tiene cita": "",
      },
    },

    "Waterdrop",
    {
      Personal: ["Rosalia Solís", "Esteban Ruíz", "Mario Ramos"],
      Encargado: "Minerva Santoro",
      Registro: {
        Nombre: "",
        Apellido: "",
        Correo: "",
        Teléfono: "",
        "motivo de la visita": [
          entrevista,
          paqueteria,
          personal,
          reunion,
          estudiante,
          otro,
        ],
        "tiene cita": "",
      },
    },

    "Lemontec",
    {
      Personal: ["Roberto Plascencia", "Tito Fuentes ", "Marcos Sura"],
      Encargado: "Joaquin Segovia",
      Registro: {
        Nombre: "",
        Apellido: "",
        Correo: "",
        Teléfono: "",
        "motivo de la visita": [
          entrevista,
          paqueteria,
          personal,
          reunion,
          estudiante,
          otro,
        ],
        "tiene cita": "",
      },
    },
    "Minu",
    {
      Personal: ["Riyadh Loranca", "Cecilia Tenorio", "Artemio Ibarra"],
      Encargado: "Martha Rivas",
      Registro: {
        Nombre: "",
        Apellido: "",
        Correo: "",
        Teléfono: "",
        "motivo de la visita": [
          entrevista,
          paqueteria,
          personal,
          reunion,
          estudiante,
          otro,
        ],
        "tiene cita": "",
      },
    },
    "Homie",
    {
      Personal: ["Octavio Vergara", "Karen Tello", "Sara Jiménez"],
      Encargado: "Ernesto Fuentes",
      Registro: {
        Nombre: "",
        Apellido: "",
        Correo: "",
        Teléfono: "",
        "motivo de la visita": [
          entrevista,
          paqueteria,
          personal,
          reunion,
          estudiante,
          otro,
        ],
        "tiene cita": "",
      },
    },

    "Shuttle Cloud",
    {
      Personal: ["Cassandra Valencia", "Valeria García", "Selene Ugalde "],
      Encargado: "Álvaro Yañez",
      Registro: {
        Nombre: "",
        Apellido: "",
        Correo: "",
        Teléfono: "",
        "motivo de la visita": [
          entrevista,
          paqueteria,
          personal,
          reunion,
          estudiante,
          otro,
        ],
        "tiene cita": "",
      },
    },
    "Ludei",
    {
      Personal: ["Romina Lezama", "Eugenia Robles", "Maximilano Reyes"],
      Encargado: "José Váldez",
      Registro: {
        Nombre: "",
        Apellido: "",
        Correo: "",
        Teléfono: "",
        "motivo de la visita": [
          entrevista,
          paqueteria,
          personal,
          reunion,
          estudiante,
          otro,
        ],
        "tiene cita": "",
      },
    },
    "Alien Vault",
    {
      Personal: ["Raúl Larios", "Tomás Sanchez", "Leonel Yunes"],
      Encargado: "Héctor Velasco",
      Registro: {
        Nombre: "",
        Apellido: "",
        Correo: "",
        Teléfono: "",
        "motivo de la visita": [
          entrevista,
          paqueteria,
          personal,
          reunion,
          estudiante,
          otro,
        ],
        "tiene cita": "",
      },
    },
    "Fora",
    {
      Personal: ["Viridiana Toscano", "Noemi Huerta", "Israel León"],
      Encargado: "Alfonso Figueroa",
      Registro: {
        Nombre: "",
        Apellido: "",
        Correo: "",
        Teléfono: "",
        "motivo de la visita": [
          entrevista,
          paqueteria,
          personal,
          reunion,
          estudiante,
          otro,
        ],
        "tiene cita": "",
      },
    },
    "Freshwater",
    {
      Personal: ["Jessica Salazar", "Harriet Noelle", "Evaristo Velarde"],
      Encargado: "Mariana Vallejo",
      Registro: {
        Nombre: "",
        Apellido: "",
        Correo: "",
        Teléfono: "",
        "motivo de la visita": [
          entrevista,
          paqueteria,
          personal,
          reunion,
          estudiante,
          otro,
        ],
        "tiene cita": "",
      },
    },
    "Sophia",
    {
      Personal: ["Gerardo Tapia", "Frida Serrano", "Alejandra Albores"],
      Encargado: "Karina Miramontes",
      Registro: {
        Nombre: "",
        Apellido: "",
        Correo: "",
        Teléfono: "",
        "motivo de la visita": [
          entrevista,
          paqueteria,
          personal,
          reunion,
          estudiante,
          otro,
        ],
        "tiene cita": "",
      },
    },
    "Wepow",
    {
      Personal: ["Citlalli Campos", "Laura Olmos", "Jorge Avendaño"],
      Encargado: "Efraín Soto",
      Registro: {
        Nombre: "",
        Apellido: "",
        Correo: "",
        Teléfono: "",
        "motivo de la visita": [
          entrevista,
          paqueteria,
          personal,
          reunion,
          estudiante,
          otro,
        ],
        "tiene cita": "",
      },
    },
    "Urbvan",
    {
      Personal: ["Sofía Valenzuela", "Daniel Guevara", "Román Cruz"],
      Encargado: "Christian Herrera",
      Registro: {
        Nombre: "",
        Apellido: "",
        Correo: "",
        Teléfono: "",
        "motivo de la visita": [
          entrevista,
          paqueteria,
          personal,
          reunion,
          estudiante,
          otro,
        ],
        "tiene cita": "",
      },
    },

    "Klar",
    {
      Personal: ["Brenda Fonseca", "Isamar Franco", "Lucas M"],
      Encargado: "Cinthia Toledo",
      Registro: {
        Nombre: "",
        Apellido: "",
        Correo: "",
        Teléfono: "",
        "motivo de la visita": [
          entrevista,
          paqueteria,
          personal,
          reunion,
          estudiante,
          otro,
        ],
        "tiene cita": "",
      },
    },
    "Moons",
    {
      Personal: ["Rogelio Muro", "Emiliano Morales", "Jimena Maciel"],
      Encargado: "Roxana Millán",
      Registro: {
        Nombre: "",
        Apellido: "",
        Correo: "",
        Teléfono: "",
        "motivo de la visita": [
          entrevista,
          paqueteria,
          personal,
          reunion,
          estudiante,
          otro,
        ],
        "tiene cita": "",
      },
    },
  ],
};
